run_locally: True       # If True, run using local files.
local_file_path: ""     # Add filepath to coding folder


gcp_project_name: "Not_required"
gcp_project_location: "Not_required"


shapefile: "Lookups/Shapefile name" # Name of the shapefile
shapefile_area_col: "" #Area column from shapefile so it can be dropped            
subnational_indicators_table_name: "Data/Data_name" # Name of the table containing the ESS format data not including file type

#path to the upper tier LA lookup for imputation
upper_tier_to_lower_tier_lookup: "Lookups/lookup_name"
upper_tier_code_column_name: ""  # Name of the upper tier code column from uppertier to lowertier lookup
lower_tier_code_column_name: ""  # Name of the lower tier code column from uppertier to lowertier lookup

#Path to the census 21 age data for the boundary changes code
census_21_table: "Lookups/lookup_name2"

#path to geography mapper from desired area to ITL1
Geog_mapper: "Lookups/lookup_name3"
ITL1_col: "" # column with ITL1 data required for ITL1 summary table
Area_col: "" # column with your desired area code
Area_name_col: "" # column with your desired area name

#Area table path for boundary changes code
LAD_area_table: "Lookups/lookup_name4"
Area_LAD_col: "" # Name of the area code column

#here you specify the indicator colomn name for each of your desired variables
custom_metrics_to_run:
  - "Example_metric_1"  
  - "Example_metric_2"

 
  

  
 #This code specifies the method of updating old boundaries to new
 #For each variable you can choose the denominator and specify a specific
 #age range if your variables only apply to a specifc age group 
metric_to_update_boundaries:
  gva:
    indicator: "Gross value added"
    start_col: 1
    denominator: "population"
  employ_rate:
    indicator: "Aged 16 to 64 years employment rate"
    start_col: 18
    end_col: 66
    denominator: "population"
  gdhi:
    indicator: "Gross disposable household income"
    start_col: 1
    denominator: "population"
  happines:
    indicator: "Happiness"
    start_col: 18
    end_col: 102
    denominator: "population"
  life_satisfaction:
    indicator: "Life satisfaction"
    start_col: 18
    end_col: 102
    denominator: "population"
  anxiety:
    indicator: "Anxiety"
    start_col: 18
    end_col: 102
    denominator: "population"
  smoking:
    indicator: "Cigarette smokers"
    start_col: 20
    end_col: 102
    denominator: "population"
  broadband:
    indicator: "Gigabit capable broadband"
    start_col: 1
    denominator: "population"
  level_3_qualifications:
    indicator: "Aged 16 to 64 years level 3 or above qualifications"
    start_col: 18
    end_col: 66
    denominator: "population"
  business_births:
    indicator: "Percentage of businesses born in 2022"
    start_col: 1
    denominator: "population"
  business_rate: 
    indicator: "Rate of businesses per 10,000 people"
    start_col: 1
    denominator: "population"
  emissions:
    indicator: "CO2 Emissions per square km"
    start_col: 3
    denominator: "area"
  electricity:
    indicator: "Domestic electricity consumption (kwh per meter)"
    start_col: 1
    denominator: "population"
  children_poverty:
    indicator: "Percentage of children in relative poverty"
    start_col: 2
    end_col: 21
    denominator: "population"
  employed_construction:
    indicator: "Percentage of people employed by sector: Construction"
    start_col: 18
    end_col: 66
    denominator: "population"
  employed_manufacture:
    indicator: "Percentage of people employed by sector: Manufacturing"
    start_col: 18
    end_col: 66
    denominator: "population"
  employed_services:
    indicator: "Percentage of people employed by sector: Services"
    start_col: 18
    end_col: 66
    denominator: "population"